### PR TITLE
Wrap ResizeObserver callback with requestAnimationFrame

### LINKED ISSUE #960: ResizeObserver loop completed with undelivered notifications
## Product

Kolibri Studio

## Expected behavior

The error message `ResizeObserver loop completed with undelivered notifications` should not occur or occur very infrequently.

## Actual behavior

The error happens repeatedly and a fullscreen overlay takes over displaying the error, most likely because it connects with rendering somehow and triggers error handling.

## Recommendations
Looking at [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver#observation_errors), it mentions this error. Currently, the KDS code uses a frame-throttle (aka `requestAnimationFrame`) at that the resizer target. Moving the frame-throttle to the `ResizeObserver` callback like the docs demonstrate could eliminate this issue, and that possibly makes sense since it says the resizer events are delivered before paint. This means the calls to the element's trigger will call the frame-throttled callback before paint, but that frame-throttled callback may not fire until after the element is destroyed or replaced during paint. Therefore, moving the frame-throttling higher up will align the logic to fire `entry.target._resizeListener` only after that has occurred, and overall, provide better performance by synchronizing all element callbacks to a single frame.

## Steps to reproduce the issue
1. Start up Studio's devserver on `unstable`
2. Open a channel
3. Click to add/upload a file
4. Upload an EPUB file
5. Click 'Finish'
6. Observe many instances of this error

## Additional information

Image

## Environment
- OS: Chrome

### PR DESCRIPTION
**Pull request by AlexVelezLl**
## Description

Wraps ResizeObserver callback in `useKResponsiveElement` with requestAnimationFrame to avoid possible resize observer issues, see https://github.com/learningequality/kolibri-design-system/issues/960.

#### Issue addressed

Closes #960.

## Changelog

  - **Description:** Wraps ResizeObserver callback in `useKResponsiveElement` with requestAnimationFrame to avoid possible resize observer issues.
  - **Products impact:** none.
  - **Addresses:** https://github.com/learningequality/kolibri-design-system/issues/960.
  - **Components:** -.
  - **Breaking:** no
  - **Impacts a11y:** no
  - **Guidance:** .

### CODE REVIEW

File: lib/composables/useKResponsiveElement.js [hunk 1]
```diff
@@ -5,11 +5,13 @@ let _resizeObserver;
 
 if (typeof window !== 'undefined' && window.ResizeObserver) {
   _resizeObserver = new ResizeObserver(entries => {
-    for (const entry of entries) {
-      if (entry.target._resizeListener) {
-        entry.target._resizeListener();
+    requestAnimationFrame(() => {
+      for (const entry of entries) {
+        if (entry.target._resizeListener) {
```
Comment (bjester) [inline lib/composables/useKResponsiveElement.js]: Since there could be some time between when the resizer callback is fired and the animation frame callback is fired, I think it would be good to check the `entry.target`. In this case, the reference should still exist, but perhaps it isn't connected anymore: https://developer.mozilla.org/en-US/docs/Web/API/Node/isConnected 

Defensive code rarely hurts!

**Review by bjester — CHANGES_REQUESTED** [review]
The changes so far look inline with the MDN docs. Adding the global animation frame means we should now also remove the use of `frame-throttle` in the same composable (line 33).

**Comment by AlexVelezLl** [comment]
Thanks @bjester! I just pushed the suggested changes :open_hands:.

**Review by bjester — APPROVED** [review]
