### PR TITLE
[KModal] Fix infinite recursive error

### LINKED ISSUE #228: Publish a channel - RangeError: Maximum call stack size exceeded.
## Observed behavior
Each time I attempt to publish a channel I see the following error in the Console: 'RangeError: Maximum call stack size exceeded.'

## Expected behavior
There should be no errors in the console.

## Errors and logs
```
channel_edit-1a9216d9cb95e16c56ab.js:1 Uncaught RangeError: Maximum call stack size exceeded.
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
flushCallbacks @ channel_edit-1a9216d9cb95e16c56ab.js:1
Promise.then (async)
timerFunc @ channel_edit-1a9216d9cb95e16c56ab.js:1
nextTick @ channel_edit-1a9216d9cb95e16c56ab.js:1
Vue.$nextTick @ channel_edit-1a9216d9cb95e16c56ab.js:1
handleOverflow @ channel_edit-1a9216d9cb95e16c56ab.js:1
handler @ channel_edit-1a9216d9cb95e16c56ab.js:1
Watcher.run @ channel_edit-1a9216d9cb95e16c56ab.js:1
flushSchedulerQueue @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
flushCallbacks @ channel_edit-1a9216d9cb95e16c56ab.js:1
Promise.then (async)
timerFunc @ channel_edit-1a9216d9cb95e16c56ab.js:1
nextTick @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
Watcher.update @ channel_edit-1a9216d9cb95e16c56ab.js:1
Dep.notify @ channel_edit-1a9216d9cb95e16c56ab.js:1
set @ channel_edit-1a9216d9cb95e16c56ab.js:1
set @ channel_edit-1a9216d9cb95e16c56ab.js:1
UPDATE_CHANNEL @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
Store._withCommit @ channel_edit-1a9216d9cb95e16c56ab.js:1
Store.commit @ channel_edit-1a9216d9cb95e16c56ab.js:1
Store.commit @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
EventEmitter.emit @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
runIfPresent @ channel_edit-1a9216d9cb95e16c56ab.js:1
onGlobalMessage @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
postMessage (async)
registerImmediate @ channel_edit-1a9216d9cb95e16c56ab.js:1
attachTo.setImmediate @ channel_edit-1a9216d9cb95e16c56ab.js:1
asap @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
callListener @ channel_edit-1a9216d9cb95e16c56ab.js:1
endMicroTickScope @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
Show 106 more frames
channel_edit-1a9216d9cb95e16c56ab.js:1 Uncaught RangeError: Maximum call stack size exceeded.
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at sentryWrapped (helpers.ts:85)
    at Sub.focusModal (channel_edit-1a9216d9cb95e16c56ab.js:1)
    at Sub.focusElementTest (channel_edit-1a9216d9cb95e16c56ab.js:1)
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
focusElementTest @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
focusModal @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
flushCallbacks @ channel_edit-1a9216d9cb95e16c56ab.js:1
Promise.then (async)
timerFunc @ channel_edit-1a9216d9cb95e16c56ab.js:1
nextTick @ channel_edit-1a9216d9cb95e16c56ab.js:1
Vue.$nextTick @ channel_edit-1a9216d9cb95e16c56ab.js:1
handleOverflow @ channel_edit-1a9216d9cb95e16c56ab.js:1
handler @ channel_edit-1a9216d9cb95e16c56ab.js:1
Watcher.run @ channel_edit-1a9216d9cb95e16c56ab.js:1
flushSchedulerQueue @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
flushCallbacks @ channel_edit-1a9216d9cb95e16c56ab.js:1
Promise.then (async)
timerFunc @ channel_edit-1a9216d9cb95e16c56ab.js:1
nextTick @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
Watcher.update @ channel_edit-1a9216d9cb95e16c56ab.js:1
Dep.notify @ channel_edit-1a9216d9cb95e16c56ab.js:1
set @ channel_edit-1a9216d9cb95e16c56ab.js:1
set @ channel_edit-1a9216d9cb95e16c56ab.js:1
UPDATE_CHANNEL @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
Store._withCommit @ channel_edit-1a9216d9cb95e16c56ab.js:1
Store.commit @ channel_edit-1a9216d9cb95e16c56ab.js:1
Store.commit @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
EventEmitter.emit @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
runIfPresent @ channel_edit-1a9216d9cb95e16c56ab.js:1
onGlobalMessage @ channel_edit-1a9216d9cb95e16c56ab.js:1
sentryWrapped @ helpers.ts:85
postMessage (async)
registerImmediate @ channel_edit-1a9216d9cb95e16c56ab.js:1
attachTo.setImmediate @ channel_edit-1a9216d9cb95e16c56ab.js:1
asap @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
callListener @ channel_edit-1a9216d9cb95e16c56ab.js:1
endMicroTickScope @ channel_edit-1a9216d9cb95e16c56ab.js:1
(anonymous) @ channel_edit-1a9216d9cb95e16c56ab.js:1
Show 106 more frames
```

## Steps to reproduce the issue
1. Publish any channel.
2. Observe the browser Console.

## Usage Details
 - OS: Windows 10
 - Browser: Chrome
 - URL: https://hotfixes.studio.learningequality.org/

### PR DESCRIPTION
**Pull request by AlexVelezLl**
## Description

Fix `RangeError: Maximum call stack size exceeded` error that was appearing in the Inherit Modal in Studio https://github.com/learningequality/studio/issues/4772.

This error was caused because in the Studio Edit Modal, we had an autocomplete VTextField component from Vuetify whose internal implementation was stealing the focus from the modal to the input. The thing is that the <input> element itself had a `@focus="onFocus"` handler, so when Vuetify does $refs.input.focus(), the `@focus` event was triggered again, but as we have a global focus listener in KModal, the KModal listener was executed first, and the VTextField onFocus was triggered just after the KModal had get the focus, so when VTextField tried to execute the `onFocus` method again, it was again stealing the focus from KModal executing again the `$refs.input.focus()`, and so on, and so forth.

This solution makes that KModal waits for this handler call to happen before requesting the focus to KModal.

#### Issue addressed
Closes #228

And once KDS is updated in Studio, it will close https://github.com/learningequality/studio/issues/4772

### Before/after screenshots

Before:

https://github.com/user-attachments/assets/53102806-d8c8-46ad-8010-3c6a49136da4

After:

https://github.com/user-attachments/assets/3f06e79b-3261-49b5-af46-0ae67ac0fff7

## Changelog

  - **Description:** Fixes infinite recursive error when KModal request the focus.
  - **Products impact:** bugfix.
  - **Addresses:** https://github.com/learningequality/studio/issues/4772, https://github.com/learningequality/kolibri-design-system/issues/228.
  - **Components:** KModal.
  - **Breaking:** no
  - **Impacts a11y:** no
  - **Guidance:** .
 

## Steps to test

You can checkout this [commit ](https://github.com/AlexVelezLl/kolibri-design-system/commit/5d1af35d0d0b1161079bab903baef69944345b9f) in Studio that was created from a commit before the nodejs upgrade.

1. Checkout that commit
2. Yarn link KDS to Studio
3. Replicate https://github.com/learningequality/studio/issues/4772

## Implementation notes

Havent found any other place where this error is happening to test if this solution works in all cases.

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical and brittle code paths are covered by unit tests
- [ ] The change is described in the changelog section above

## Reviewer guidance

- [ ] Is the code clean and well-commented?
- [ ] Are there tests for this change?
- [ ] Are all UI components LTR and RTL compliant (if applicable)?
- [ ] _Add other things to check for here_

### CODE REVIEW

File: lib/KModal.vue [hunk 1]
```diff
@@ -372,7 +372,10 @@
         }
         // focus has escaped the modal - put it back!
         if (!this.$refs.modal.contains(target)) {
-          this.focusModal();
+          this.$nextTick(() => {
+            // flush any pending DOM/focus updates
```
Comment (MisRob) [inline lib/KModal.vue]: May be nice to reference the issue https://github.com/learningequality/kolibri-design-system/issues/228, I don't think we will connect dots after a few months :)

**Review by MisRob — APPROVED** [review]
` VTextField`, you thief!

Tricky tricky. Nice work @AlexVelezLl.

**Comment by AlexVelezLl** [comment]
Thanks Misha! I've just pushed a commit referencing the issue :hugs:. Merging!
