### PR TITLE
Fix visually hidden style not taking effect, allow KTextbox label to be visually hidden

### LINKED ISSUE #1163: Investigate why visuallyhidden class doesn't take effect in Studio
❌ **This issue is not open for contribution. Visit <a href="https://learningequality.org/contributing-to-our-open-code-base/" target="_blank">Contributing guidelines</a>** to learn about the contributing process and how to find suitable issues.

## Observed behavior

 `class="visuallyhidden"` set _inside_ KDS components, e.g. `KCard`, doesn't take effect in Studio.

## Expected behavior

Internal visually hidden behavior should work for KDS components without the need to add `visuallyhidden` class to any Kolibri applications.

### LINKED ISSUE #1166: [KTextbox]: Allow label to be passed via slot
❌ **This issue is not open for contribution. Visit <a href="https://learningequality.org/contributing-to-our-open-code-base/" target="_blank">Contributing guidelines</a>** to learn about the contributing process and how to find suitable issues.

## Current behavior

The only way to pass a label is via the `label` prop.

## Desired behavior

- Label can be passed either via `label` prop or `label` slot
- There is validation that throws a warning in case a label is not passed via one of them
- There is a documentation on how to use and not use the `label` slot

## Value add

- Supports use-cases when displaying a label visually is not desired (e.g. token readonly input in Studio's [channel collections table](https://github.com/learningequality/studio/issues/5529))

```
<KTextbox>
  <template #label>
    <span class="visuallyhidden">Label</span> 
  </template>
</KTextbox>
```

- Will allow to get rid of implementations when visual requirements led to label being bypassed by `label=" "`, such as [here](https://github.com/learningequality/studio/blob/d9f08c3eda782a9f7aadf1237c64f25efe353eb5/contentcuration/contentcuration/frontend/settings/pages/Storage/RequestForm.vue#L173-L183) and other places, resulting in poor a11y due to missing labels.

- Allows for any future customization of labels, should the need arise

## Possible tradeoffs

General tradeoffs related to allowing anything be passed. Documentation will have guidance though.

### PR DESCRIPTION
**Pull request by MisRob**
## Description

- Fixes _internal_ visually hidden style (`KCard` example [here](https://github.com/learningequality/kolibri-design-system/blob/64c654cf0e246e14d4aa458fff41c5b0236758d9/lib/cards/KCard.vue#L32) + [here](https://github.com/learningequality/studio/pull/5564/files#diff-babee32b23e7321868294d22e9406a4d1a1c82e96871178bad171d1300e54163L465-L475)) not taking effect in KDS components when used from an application
  - By moving the style from documentation styles to library styles, and adding a new installation step to register library styles in applications

- As a side effect, above also exposes the `.visuallyhidden` class to be used for any component, not just KDS.

- Allows `KTextbox` label to be passed via slot and adds documentation on how to achieve visually hidden label

- Also has few maintenance commits for related documentation and test suite

#### Issue addressed

- Fixes https://github.com/learningequality/kolibri-design-system/issues/1163
- Studio companion PR https://github.com/learningequality/studio/pull/5564
- Fixes https://github.com/learningequality/kolibri-design-system/issues/1166

## Steps to test

- Preview updated documentation
  - [Installation: 2. Register global styles](https://deploy-preview-1169--kolibri-design-system.netlify.app/installation#register-global-styles)
  - [Helper styles](https://deploy-preview-1169--kolibri-design-system.netlify.app/styling#helper-styles)
  - [KTextbox: Input with label](https://deploy-preview-1169--kolibri-design-system.netlify.app/ktextbox#with-label)
  - [KTextbox: Visually hidden label](https://deploy-preview-1169--kolibri-design-system.netlify.app/ktextbox#visually-hidden-label)

## Changelog

  - **Description:** Fixes internal visually hidden style not taking effect in KDS components, and exposes the `.visuallyhidden` class as public
  - **Products impact:** bugfix
  - **Addresses:** https://github.com/learningequality/kolibri-design-system/issues/1163
  - **Components:** -
  - **Breaking:** no
  - **Impacts a11y:** no
  - **Guidance:** Import KDS styles in the main application stylesheet with `@import '~kolibri-design-system/lib/styles/common';` as described in https://design-system.learningequality.org/installation#register-global-styles. Cleanup custom `.visuallyhidden` class from application styles. See https://design-system.learningequality.org/#helper-styles.

  - **Description:** Allows `KTextbox` label to be passed via slot
  - **Products impact:** new API
  - **Addresses:** https://github.com/learningequality/kolibri-design-system/issues/1166
  - **Components:** `KTextbox`
  - **Breaking:** no
  - **Impacts a11y:** yes
  - **Guidance:** -

### CODE REVIEW

File: lib/KTextbox/index.vue [hunk 1]
```diff
@@ -29,6 +29,13 @@
       @focus="emitFocus"
       @blur="emitBlur"
     >
+      <!--@slot Label. Alternative to the label prop. -->
```
Comment (akolson) [inline lib/KTextbox/index.vue]: I'm not sure why the description for the `label` isn't showing up in the docs? 

Image

**Review by akolson — COMMENTED** [review]
LGTM! Thanks @MisRob. I left a comment about the docs

File: lib/KTextbox/index.vue (hunk 1 above)
Comment (MisRob) [reply lib/KTextbox/index.vue]: Thank you. I placed the comment wrongly. It needs to be right above the slot itself. Fixed.

Screenshot from 2025-11-24 16-24-20

**Review by akolson — APPROVED** [review]
Approved. Thanks @MisRob
