### PR TITLE
Node.js upgrade to v18 along with dependency upgrades and linting fixes

### LINKED ISSUE #439: Upgrade to NodeJS 18
## Blocks

https://github.com/learningequality/kolibri-design-system/issues/510

## Summary

KDS still uses NodeJS 12 which is no longer maintained or supported. At some point in the future, doubtless Github Actions will cease supporting this, which will cause our Github Actions to break.

We should upgrade to use NodeJS 16 which will require the following sequence of steps:

```[tasklist]
### Tasks
- [ ] https://github.com/learningequality/kolibri/pull/9698
- [ ] https://github.com/learningequality/kolibri/pull/12722
- [ ] https://github.com/learningequality/kolibri/issues/8454
- [ ] Remove dependency on kolibri-tools and replace with the newly independent kolibri-formatting-tools or whatever the name ends up being
- [ ] In conjunction with this update the NodeJS version to the version required for the formatting tools (currently 16, but will become 18 in the future)
- [ ] Upgrade to VueJS 2.7
- [ ] Upgrade any build dependencies by the smallest version increment possible to have compatibility with the new NodeJS version (to avoid completely breaking the build system or requiring a more holistic upgrade)
- [ ] https://github.com/learningequality/kolibri/issues/10636
```

### PR DESCRIPTION
**Pull request by bjester**
## Description

Upgrades Node.js to v18, along with Kolibri-Tools to v0.16, Jest to v29 and Nuxt to v2.15. Additionally, this pins dependencies in order to maintain compatibility between Nuxt and kolibri-tools, applies fixes for new linting errors, and cleans up testing output through better error handling.

#### Issue addressed

Addresses https://github.com/learningequality/kolibri-design-system/issues/439

## Changelog

  - **Description:** Upgrades Node.js to v18, along with Kolibri-Tools to v0.16, Jest to v29 and Nuxt to v2.15
  - **Products impact:** none
  - **Addresses:** #439 
  - **Components:** none
  - **Breaking:** no
  - **Impacts a11y:** no
  - **Guidance:** Netlify configuration needs to be updated to use v18 as well

  - **Description:** Component error handling now use `@error` listener to avoid polluting test output, nor suppressing `console.*` in tests 
  - **Products impact:** any
  - **Addresses:** n/a
  - **Components:** `KImg`, `KTabs`, `KTabsList`
  - **Breaking:** yes
  - **Impacts a11y:** no
  - **Guidance:** The `KImg` component may now emit an `Error` object in its `@error` listener when incorrectly configured, in addition to an `UiEvent|Event` when an image fails to load. Consumers should type check the value.

## Steps to test

1. Run `yarn run test`
2. Verify tests pass
3. Run `yarn run dev`
4. Verify documentation

### At a high level, how did you implement this?

- Upgraded Node.js
- Upgraded dependencies to highest version we could support
- Cleaned up test output throwing warnings and other errors
- Pinned dependency resolutions as needed

### Does this introduce any tech-debt items?

Yes https://github.com/learningequality/kolibri-design-system/issues/646

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [x] Critical and brittle code paths are covered by unit tests
- [x] The change is described in the changelog section above

## Reviewer guidance

- [x] Is the code clean and well-commented?
- [x] Are there tests for this change?
- [ ] Are all UI components LTR and RTL compliant (if applicable)?
- [ ] _Add other things to check for here_

## After review

- [ ] The changelog item has been pasted to the `CHANGELOG.md`

### CODE REVIEW

**Comment by bjester** [comment]
Before I actually update the changelog file, please let me know how my notes look in the PR.

**Comment by bjester** [comment]
Noting we must update the Node.js version in Netlify before merging

File: lib/KImg/index.vue [hunk 1]
```diff
@@ -356,20 +362,33 @@
     },
     created() {
       if (!this.isDecorative && !this.altText) {
-        throw new Error('Missing required prop - provide altText or indicate isDecorative');
+        this.onError(new Error('Missing required prop - provide altText or indicate isDecorative'));
```
Comment (AlexVelezLl) [inline lib/KImg/index.vue:315]: Are these changes made only to improve the tests? Or is there a rule against doing throw inside a component?

File: lib/KImg/index.vue [hunk 2]
```diff
@@ -356,20 +362,33 @@
...
+       * - the aspect ratio is invalid => error obj
+       *
+       * @param {UIEvent|Error} event
+       */
       onError(event) {
-        /**
-         * Emitted when the image fails to load. The DOM event that triggered the error is available in the payload.
-         */
-        this.$emit('error', event);
+        if (this.$listeners && this.$listeners.error) {
```
Comment (AlexVelezLl) [inline lib/KImg/index.vue:331]: In my opinion, I think it would be better to throw another event for the errors objects, since they are for validation, and I would think it would be a bit tedious for the consumer to put validations in the @error handler to know if the error thrown is for a load error. But I would like to hear more thoughts on this.

File: lib/tabs/__tests__/KTabsList.spec.js [hunk 3]
```diff
@@ -28,20 +37,29 @@ const TABS_WITH_ROUTES = [
...
 
-  afterAll(() => {
-    console.error.mockRestore();
+  beforeEach(() => {
+    errorListener = jest.fn();
   });
 
   afterEach(() => {
-    console.error.mockClear();
+    errorListener = null;
```
Comment (AlexVelezLl) [inline lib/tabs/__tests__/KTabsList.spec.js:58]: (Just curious) Is there any benefit to preferring this pattern to defining a single jest.fn() and doing errorListener.mockClear after each test?

File: .github/workflows/tests.yml [hunk 4]
```diff
@@ -25,7 +25,7 @@ jobs:
     - name: Use Node.js
       uses: actions/setup-node@v4
       with:
-        node-version: '10.x'
+        node-version: '18.x'
```
Comment (AlexVelezLl) [inline .github/workflows/tests.yml:28]: I think we can also update the node-version in the npm-publish workflow?

File: dev_docs/01_getting_started.md [hunk 5]
```diff
@@ -4,8 +4,8 @@ The design system has two primary parts, the UI component library [`/lib`](../li
 
 ## Prerequisites
 
-- Node.js 10.x (see [Node Version Manager](https://github.com/nvm-sh/nvm))
-- Yarn 1.x
+- Node.js 18.x (see [Node Version Manager](https://github.com/nvm-sh/nvm))
+- Yarn >=1.22.22
```
Comment (AlexVelezLl) [inline dev_docs/01_getting_started.md:8]: Now when I run `yarn lint`, `yarn dev` I get this error because I dont have pnpm installed:

```
> yarn lint
yarn run v1.22.22
$ kolibri-tools lint --pattern '**/*.{js,vue,scss,less,css}' --ignore '**/node_modules/**,**/.nuxt/**,**/dist/**,**/lib/KIcon/precompiled-icons/**,**/lib/keen/**,**/docs/environment.js,**/docs/jsdocs.js'

Kolibri CLI: Error: Command failed: "pnpm --version"

stderr:
Volta error: Could not find executable "pnpm"

Use `volta install` to add a package to your toolchain (see `volta help install` for more info).
Error details written to /home/alexvelezll/.volta/log/volta-error-2024-05-27_11_10_15.764.log


original error message:
Command failed: pnpm --version
Volta error: Could not find executable "pnpm"

Use `volta install` to add a package to your toolchain (see `volta help install` for more info).
Error details written to /home/alexvelezll/.volta/log/volta-error-2024-05-27_11_10_15.764.log


error Command failed with exit code 1.
```

Does the new version of kolibri-tools require pnpm to be installed? If so I think we need to add this to our prerequisites.

**Review by AlexVelezLl — COMMENTED** [review]
Thank you @bjester! This looks great to me :open_hands:, I left just some questions. And just a small note: Could you add your changelog items to [CHANGELOG.md](https://github.com/learningequality/kolibri-design-system/blob/release-v4/CHANGELOG.md) please?

File: lib/KImg/index.vue (hunk 2 above)
Comment (bjester) [reply lib/KImg/index.vue:331]: It isn't tedious IMO. A type check on the passed object is sufficient. This is pretty common practice in processing captured errors, i.e. think multiple catch blocks for try block.

File: lib/tabs/__tests__/KTabsList.spec.js (hunk 3 above)
Comment (bjester) [reply lib/tabs/__tests__/KTabsList.spec.js:58]: The only benefit is that it is more explicit. If `errorListener` is used when it shouldn't then this will error, and being this is a mock that should only apply during a test, it could theoretically capture issues if the component was doing something asynchronous that extended beyond the test run, which is a troublesome issue.

File: lib/KImg/index.vue (hunk 1 above)
Comment (bjester) [reply lib/KImg/index.vue:315]: The existing behavior still functions as expected, except when an `@error` listener is used. The main issue with this is that it isn't an error that can be caught explicitly with a try/catch, due to how Vue handles rendering in the event loop. I highly advise against mocking the console in tests because that could conceal real issues. Similarly, because this can't be caught in the test, it pollutes the test output which further obscures what's an actual issue. So in summary, I believe there are benefits on all sides.

File: .github/workflows/tests.yml (hunk 4 above)
Comment (bjester) [reply .github/workflows/tests.yml:28]: Good catch! Looks like I missed that one

File: dev_docs/01_getting_started.md (hunk 5 above)
Comment (bjester) [reply dev_docs/01_getting_started.md:8]: There should be no requirement on `pnpm`-- nothing in regards to that has changed.

Comment (bjester) [reply dev_docs/01_getting_started.md:8]: Have you previously run a `corepack` command on your system?

I don't think this will resolve the issue, but you could try adding `export SKIP_YARN_COREPACK_CHECK=1` to your terminal env.

**Comment by bjester** [comment]
Hmm linting was passing, but now it isn't :thinking: I'll take a look

File: lib/KImg/index.vue (hunk 1 above)
Comment (AlexVelezLl) [reply lib/KImg/index.vue:315]: Alright, makes sense =)

File: lib/KImg/index.vue (hunk 2 above)
Comment (AlexVelezLl) [reply lib/KImg/index.vue:331]: Oh well, I said it more because normally an onError handler in  tags is usually more for handling image loading errors, and it seemed appropriate to me that a consumer expects a KImg onError to be quite similar to an  onError, but, I guess doing validations doesn't hurt either.

File: lib/tabs/__tests__/KTabsList.spec.js (hunk 3 above)
Comment (AlexVelezLl) [reply lib/tabs/__tests__/KTabsList.spec.js:58]: Oh, that's very interesting. Thanks!

File: lib/KImg/index.vue (hunk 2 above)
Comment (bjester) [reply lib/KImg/index.vue:331]: You're right, it is a little awkward in that respect. The sense that I got is that we wouldn't normally handle the other errors and they shouldn't arise in 'production', since those seem most useful within development. So the end result means you should structure your listener to re-raise anything it doesn't expect, which isn't too dissimilar from a typical catch

Comment (bjester) [reply lib/KImg/index.vue:331]: ^^ And a positive from this is that it promotes writing more explicit code

File: dev_docs/01_getting_started.md (hunk 5 above)
Comment (AlexVelezLl) [reply dev_docs/01_getting_started.md:8]: Hmm, no, that didn't solve it. It's weird because I tried to run it on my Windows machine, where I also don't have Pnpm, and it worked there :thinking:

In my Ubuntu machine I finally installed pnpm using `volta install pnpm` and then `yarn lint` worked.

**Comment by MisRob** [comment]
> Before I actually update the changelog file, please let me know how my notes look in the PR.

Thank you, @bjester, to me it looks well and clear, and I appreciate the guidance

**Comment by MisRob** [comment]
Hi @bjester, thanks a lot - lots of work!

I've switched to this branch, then `nvm use 18`, then `yarn install`, and finally `yarn dev`. It seems the devserver initialization gets stuck and I can't access http://localhost:4000/ as usual

```
michaela@michaela:~/dev/kolibri-design-system$ yarn run dev
yarn run v1.22.17
$ npm-run-all --parallel dev-only _lint-watch-fix _api-watch pregenerate
$ yarn lint -w -m
$ chokidar "**/lib/**" -c "node utils/extractApi.js"
$ nuxt --port 4000
$ node utils/pregenerate.js
$ kolibri-tools lint --pattern '**/*.{js,vue,scss,less,css}' --ignore '**/node_modules/**,**/.nuxt/**,**/dist/**,**/lib/KIcon/precompiled-icons/**,**/lib/keen/**,**/docs/environment.js,**/docs/jsdocs.js' -w -m
ℹ  Netlify environment variables:                                     11:44:01
    NETLIFY:        undefined
    BRANCH:         undefined
    PULL_REQUEST:   undefined
    REPOSITORY_URL: undefined
ℹ Wrote environment to /home/michaela/dev/kolibri-design-system/docs/environment.js

 WARN  mode option is deprecated. You can safely remove it from nuxt.config

ℹ Wrote rst icon replacement strings to /home/michaela/dev/kolibri-design-system/docs/rstIconReplacements.txt

ℹ NuxtJS collects completely anonymous data about usage.          11:44:01 AM
  This will help us improve Nuxt developer experience over time.
  Read more on https://git.io/nuxt-telemetry

? Are you interested in participating? (Y/n) Kolibri Linter: Initializing watcher for the following patterns: **/*.{js,vue,scss,less,css}

 WARN  Could not extract docs from /home/michaela/dev/kolibri-design-system/lib/KThemePlugin.js

ℹ Wrote jsdocs to /home/michaela/dev/kolibri-design-system/docs/jsdocs.js
add:node_modules/.bin/acorn
add:node_modules/autoprefixer/node_modules/.bin/browserslist
add:node_modules/bonjour-service/node_modules/.bin/multicast-dns
...
add:node_modules/.bin/webpack-cli
add:node_modules/.bin/webpack-dev-server
Watching "**/lib/**" ..

 WARN  Could not extract docs from /home/michaela/dev/kolibri-design-system/lib/KThemePlugin.js

ℹ Wrote jsdocs to /home/michaela/dev/kolibri-design-system/docs/jsdocs.js
```

Can you see something problematic in the log above or have some recommendations on how to best proceed with debuggin?

**Comment by MisRob** [comment]
I wonder if this is related to the problem with the devserver.

`yarn generate` gives me this error
Screenshot from 2024-06-05 11-50-49

**Comment by MisRob** [comment]
Good news is that I could successfully run

- yarn lint
- yarn lint-fix
- yarn lint-watch
- yarn pregenerate
- yarn dev-only
- yarn precompile-svgs
- yarn precompile-custom-svgs
- yarn _lint-watch-fix
- yarn test
- yarn _api-watch

So it is only `generate` and `dev` causing trouble. I use Ubuntu.

File: lib/KDateRange/KDateInput.vue [hunk 6]
```diff
@@ -28,9 +28,10 @@
 
 <script>
 
-  import { v4 as uuidv4 } from 'uuid';
   import KTextBox from '../KTextbox';
 
+  let uuid = 0;
```
Comment (MisRob) [inline lib/KDateRange/KDateInput.vue:41]: If we used the same approach from another component (instead of using `uuid` library), could there be any conflicts?

File: lib/KImg/index.vue [hunk 7]
```diff
@@ -296,12 +296,18 @@
...
+        };
         if (!this.aspectRatio) {
-          return {
-            rootContainer: {},
-            ratioContainer: {},
-            img: {},
-          };
+          return defaultValue;
+        }
+        // Avoid accessing unset indices through `this.ratio`
```
Comment (MisRob) [inline lib/KImg/index.vue:257]: Nice

**Comment by MisRob** [comment]
Also just read the code and haven't noticed any issues

**Review by MisRob — COMMENTED** [review]
Also just read the code and haven't noticed any issues, just have one question about `uuid`

**Comment by MisRob** [comment]
@bjester Upgrading yarn to v1.22.22 as discussed helped me with `yarn dev` that works now. I still see problem with `yarn generate`. But we can have a look whether that's actually a regression or if it was present before (can try that out but later)

Screenshot from 2024-06-05 18-09-10

**Comment by bjester** [comment]
I have replicated @MisRob's issue. It seems to stem from incompatibility with hoisted postcss packages. I will look at fixing it

File: lib/KDateRange/KDateInput.vue (hunk 6 above)
Comment (bjester) [reply lib/KDateRange/KDateInput.vue:41]: Only if the ID prefix wasn't already unique

**Comment by MisRob** [comment]
I will unassign myself from the asigned reviewer role for now so I don't block it as I will be away for two weeks, back on July 8. If it's still open when I'm back and I can help, please ping me :)! Thanks.

**Comment by MisRob** [comment]
I will unassign myself from the asigned reviewer role for now since everything is reviewed at this point. So that I don't block another round of review as I will be away for two weeks, back on July 8. If it's still open when I'm back and I can help, please ping me :)! Thanks.

File: CHANGELOG.md
Comment (MisRob) [inline CHANGELOG.md:1]: Leaving a note here that before merging it'd be good to revert CHANGELOG.md changes since the new GH action will now update the CHANGELOG.md after merging this PR by pasting the changelog from the PR description. Otherwise we'd have duplicate entries.

**Comment by AlexVelezLl** [comment]
Hi! According to our conversation with @rtibbles. This PR should be retargeted to the develop branch.

File: docs/pages/kcardgrid.vue [hunk 8]
```diff
@@ -278,51 +388,53 @@
...
-                },
-                {
-                  breakpoints: [4, 5, 6, 7],
-                  cardsPerRow: 4,
-                },
-              ],
-            };
-          },
-        };
+        export default { ... data() { return { layoutOverride: [ { breakpoints: [0, 1], columnGap:
```
Comment (AlexVelezLl) [inline docs/pages/kcardgrid.vue]: I think this change should be reverted and we need to add the  comment here too, as its hard to read now.

File: docs/pages/kcardgrid.vue [hunk 9]
```diff
@@ -454,39 +571,50 @@
...
       <DocsShowCode language="javascript">
-        export default {
-          ...
-          computed: {
-            slicedPills() {
-              return pills.slice(0, 2);
-            },
-          },
-        };
+        export default { ... computed: { slicedPills() { return pills.slice(0, 2); }, }, };
```
Comment (AlexVelezLl) [inline docs/pages/kcardgrid.vue]: idem

File: docs/pages/kcardgrid.vue [hunk 10]
```diff
@@ -500,14 +628,9 @@
...
       <DocsShowCode language="javascript">
-        import useKResponsiveWindow from 'kolibri-design-system/lib/composables/useKResponsiveWindow';
-
-        export default {
-          setup() {
-            const { windowBreakpoint } = useKResponsiveWindow();
-            return { windowBreakpoint };
-          },
-        };
+        import useKResponsiveWindow from
```
Comment (AlexVelezLl) [inline docs/pages/kcardgrid.vue]: idem

File: docs/pages/kcardgrid.vue [hunk 11]
```diff
@@ -677,42 +866,43 @@
...
-                },
-                {
-                  breakpoints: [4, 5, 6, 7],
-                  height: '220px',
-                  orientation: 'horizontal'
-                }
-              ],
-            };
-          },
+        export default { ... data() { return { skeletonsConfig: [ { breakpoints: [0, 1, 2, 3, 4, 5,
```
Comment (AlexVelezLl) [inline docs/pages/kcardgrid.vue]: Idem

File: docs/pages/klistwithoverflow.vue [hunk 12]
```diff
@@ -90,39 +90,28 @@
...
-          return {
-            items: [
-              { label: "Item 1", icon: "edit" },
-              { label: "Item 2", icon: "edit" },
-              { label: "Item 3", icon: "edit" },
-              // ...
-              { label: "Item 12", icon: "edit" },
-            ]
-          };
+        data() { return { items: [ { label: "Item 1", icon: "edit" }, { label: "Item 2", icon:
```
Comment (AlexVelezLl) [inline docs/pages/klistwithoverflow.vue]: idem

File: docs/pages/klistwithoverflow.vue [hunk 13]
```diff
@@ -168,21 +154,11 @@
...
-            items: [
-              { label: "Item 1", icon: "edit" },
-              { label: "Item 2", icon: "edit" },
-              { type: "divider" },
-              { label: "Item 4", icon: "edit" },
-              // ...
-            ]
-          };
-        },
+        data() { return { items: [ { label: "Item 1", icon: "edit" }, { label: "Item 2", icon:
```
Comment (AlexVelezLl) [inline docs/pages/klistwithoverflow.vue]: idem

File: docs/pages/styling/index.vue [hunk 14]
```diff
@@ -1,175 +1,212 @@
...
       <DocsShowCode language="css">
-        @import '~kolibri-design-system/lib/styles/definitions'
-
-        .box {
-          @extend %dropshadow-2dp;
-
-          border-radius: $radius;
-          text-align: center;
-        }
+        @import '~kolibri-design-system/lib/styles/definitions' .box { @extend %dropshadow-2dp;
```
Comment (AlexVelezLl) [inline docs/pages/styling/index.vue]: idem

File: docs/pages/styling/index.vue [hunk 15]
```diff
@@ -1,175 +1,212 @@
...
-        }
-
-        .box-2dp {
-          @extend %dropshadow-2dp;
-        }
-
-        .box-6dp {
-          @extend %dropshadow-6dp;
-        }
+        @import '~kolibri-design-system/lib/styles/definitions' .box-1dp { @extend %dropshadow-1dp;
```
Comment (AlexVelezLl) [inline docs/pages/styling/index.vue]: idem

File: docs/pages/usekliveregion.vue [hunk 16]
```diff
@@ -88,7 +155,7 @@
 
 <script>
 
-  import { ref } from '@vue/composition-api';
+  import { ref } from 'vue';
```
Comment (AlexVelezLl) [inline docs/pages/usekliveregion.vue:158]: :tada: :tada: :tada:

File: lib/KDropdownMenu.vue [hunk 17]
```diff
@@ -145,9 +146,11 @@
       window.removeEventListener('keydown', this.handleOpenMenuNavigation, true);
     },
     methods: {
-      handleOpen() {
+      async handleOpen() {
```
Comment (AlexVelezLl) [inline lib/KDropdownMenu.vue:149]: Was this a change made from the linter?  :0

**Review by AlexVelezLl — CHANGES_REQUESTED** [review]
Thanks @rtibbles and @bjester! This is looking good. I have ran all the package.json scripts and havent got any errors on any of them, and I have briefly checked the rendered docs pages, and havent noticed anything wrong with it. I just noted some js code examples that were incorrectly formatted.

And I was also wondering if we should include the code format commits to a `.git-blame-ignore-revs` file, similar to what we did in Kolibri to avoid losing the blame of those lines.

File: lib/KDropdownMenu.vue (hunk 17 above)
Comment (rtibbles) [reply lib/KDropdownMenu.vue:149]: For some reason the linter didn't like the double nested `$nextTick` call unless it used `await this.$nextTick()` twice instead - so this seemed like the easiest way to workaround it. It feels like maybe a bug in the linter, but this also feels more readable, so I didn't see a concern.

Comment (AlexVelezLl) [reply lib/KDropdownMenu.vue:149]: Cool!

**Review by AlexVelezLl — APPROVED** [review]
Code changes looks good, all package.json scripts are working as expected and netlify deploy using node 18 was successful!! Thanks!
