### PR TITLE
various fixes for console errors, code examples, and netlify styling

### LINKED ISSUE #181: Netlify PR builds styling is broken
## Product
KDS

## Expected behavior

Netlify PR builds should represent production-like builds and be styled properly.

## Actual behavior

This is the KIconButtons I see on #165 's deployment (tooltips visible, buttons squared and white)

screenshot-deploy-preview-165--kolibri-design-system netlify app-2021 02 25-10_14_41

But what I see when I pull and run locally:

screenshot-localhost_4000-2021 02 26-12_06_58

Another in KButton (all white button formatting issues)

screenshot-deploy-preview-165--kolibri-design-system netlify app-2021 02 26-12_01_40

Locally:

screenshot-localhost_4000-2021 02 26-12_08_09

## Steps to reproduce the issue
Go to #165 and check the button examples in the deployment preview.

Then pull locally and look at the same page side-by-side.

## Environment
- OS: Debian 10
- Browser version: Chrome 83.something

### PR DESCRIPTION
**Pull request by indirectlylit**
## Description

* Makes all pages lowercase because [Netlify forces all URLs to lowercase](https://answers.netlify.com/t/my-url-paths-are-forced-into-lowercase/1659)
* Fixes a number of console errors on various pages
* Improves checkbox and switch examples

#### Issue addressed

fixes #181

### Before/after screenshots

**Styling on Netlify:**

| before | after |
|--|--|
| image | image |

**Button examples:**

| before | after |
|---|---|
|  |  |
|  |  |

## Steps to test

Navigate to every page, looking for broken styling and console errors

## Implementation notes

Pages and URL paths are now all lowercase, while page titles remain case-sensitive

## Reviewer guidance

- [x] Is the code clean and well-commented?
- [ ] Are there tests for this change?
- [ ] Are all UI components LTR and RTL compliant (if applicable)?
- [ ] _Add other things to check for here_

### CODE REVIEW

File: docs/tableOfContents.js [hunk 1]
```diff
@@ -258,19 +258,19 @@ export default [
     autoSort: true,
     pages: [
       new Page({
-        path: '/KThemePlugin',
+        path: '/kthemeplugin',
```
Comment (nucleogenesis) [inline docs/tableOfContents.js:261]: I hope you automated this somehow instead of typing every one of these out :fearful:

**Review by nucleogenesis — APPROVED** [review]
Great work!

File: docs/tableOfContents.js (hunk 1 above)
Comment (indirectlylit) [reply docs/tableOfContents.js:261]: yup - a little regex and a little sublime text magic :D
