### PR TITLE
Issues with keyboard navigation on KDropdownMenu

### LINKED ISSUE #588: Issues with keyboard navigation on KDropdownMenu
## Product
Noted in Studio, and in the [KDS Docs](https://release-v3--kolibri-design-system.netlify.app/klistwithoverflow/) on the last example of KListWithOverflow.

## Expected behavior

Two things are not working very well right now:
* When the list has dividers, the keyboard navigation should ignore them and focus on the next or previous item in the list.
  * In the `options` list, We can include dividers with a `{ type: "Divider" }` object.
* When the user presses `tab` or `esc`, we should return the focus to the last element focused before KDropdownMenu was active. This can be done by saving the `document.activeElement` before focusing the first option of the dropdown menu.

## Actual behavior
* Right now, the focus doesn't change when there are dividers and we want to focus the next item, and we can't jump the dividers.
* As KDropdownMenu is rendered in the body element, when `esc` or `tab` is pressed, the focus returns to the first focusable element on the document after a second. But before the focus returns to the body, the next option in the menu is focused, and after a second, the menu closes, which is a bit misleading since, at first, it seems that we could navigate through the menu with a tab.

## Steps to reproduce the issue
1. Go to the [KListWithOverflow documentation](https://release-v3--kolibri-design-system.netlify.app/klistwithoverflow/).
2. Click on the box of the last list example.
3. Navigate with the keyboard through the dropdown menu and note the issues described above.

  ## Additional information

https://github.com/learningequality/kolibri-design-system/assets/51239030/427bdbd5-b02b-4b73-bec1-d54299940b50

### PR DESCRIPTION
**Pull request by Sahil-Sinha-11**
…p down position

#### Issue addressed

Addresses #588

### After Video
[](https://github.com/user-attachments/assets/549e99bb-8a8c-414f-9dd7-414fde337327)

## Changelog

  - **Description:** keyboard navigation on KDropdownMenu 
  - **Products impact:** bugfix.
  - **Addresses:**Issues with keyboard navigation on KDropdownMenu #588.
  - **Components:** kDropdownMenu.vue
  - **Breaking:** -
  - **Impacts a11y:** - 
  - **Guidance:** -

## Steps to test

1. Step 1
2. Step 2
3. ...

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical and brittle code paths are covered by unit tests
- [ ] The change is described in the changelog section above

## Reviewer guidance

- [ ] Is the code clean and well-commented?
- [ ] Are there tests for this change?
- [ ] Are all UI components LTR and RTL compliant (if applicable)?
- [ ] _Add other things to check for here_

### CODE REVIEW

File: lib/KDropdownMenu.vue [hunk 1]
```diff
@@ -175,19 +175,36 @@
...
         // set current element and its siblings
         let focusedElement = document.activeElement;
-        let sibling = focusedElement.nextElementSibling;
-        let prevSibling = focusedElement.previousElementSibling;
+        // let sibling = focusedElement.nextElementSibling;
+        // let prevSibling = focusedElement.previousElementSibling;
+
+        //function to check if the sibling is divider
+        const isDivider = element => {
+          return element && element.classList.contains('is-divider');
```
Comment (AlexVelezLl) [inline lib/KDropdownMenu.vue]: This is a good way to determine if the element is a divider, but is a little specific. If anything changes and in the future we get rid of this specific class. This would break this condition.

A more general solution could be to ask if the element has a tabIndex >= 0, so this means it is focusable and with this, we can skip the dividers.

File: lib/KDropdownMenu.vue [hunk 2]
```diff
@@ -175,19 +175,36 @@
...
           prevSibling
             ? this.$nextTick(() => prevSibling.focus())
             : this.$nextTick(() => lastChild.focus());
           // DOWN arrow
         } else if ((event.key == 'ArrowDown' || event.keyCode == 40) && popoverIsOpen) {
           event.preventDefault();
+
+          //Chekcing if next sibling is divider and skipping it
+          let sibling = focusedElement.nextElementSibling;
+          while (sibling && isDivider(sibling)) {
```
Comment (AlexVelezLl) [inline lib/KDropdownMenu.vue]: We could write two separate methods here, to breakdown a little bit this method. so we can just do something like

```javascript
const sibling = this.getNextFocusableSibling(focusedElement);
const prevSibling = this.getPrevFocusableSibling(focusedElement);
```

File: lib/KDropdownMenu.vue (hunk 1 above)
Comment (Sahil-Sinha-11) [reply lib/KDropdownMenu.vue]: Oh right, that seems more logical to skip any other element [like divider] in a more generalized way. Thanks @AlexVelezLl .

File: lib/KDropdownMenu.vue (hunk 2 above)
Comment (Sahil-Sinha-11) [reply lib/KDropdownMenu.vue]: Hey @AlexVelezLl , I've defined prevSibling Already here
Screenshot 2024-11-11 at 12 21 48 AM
and the variable sibling Is for next focused element.

**Comment by Sahil-Sinha-11** [comment]
Hey @Sahil-Sinha-11,  I made the suggested changes. 🤗 
PS: sorry for the late reply, actually my university exams are next week so quite loaded with tests. 😅

**Comment by Sahil-Sinha-11** [comment]
Hey @AlexVelezLl , the focus works like this, should I return it to the last focused button?

https://github.com/user-attachments/assets/4c1a3ca4-6bd5-444a-929d-a421ef216488

File: lib/KDropdownMenu.vue (hunk 2 above)
Comment (AlexVelezLl) [reply lib/KDropdownMenu.vue]: Yes, my suggestion was more to avoid writing more logic to query the next/previouss element in the same `handleOpenMenuNavigation` method. So lets define two new methods in this component `getNextFocusableSibling` and `getPrevFocusableSibling` where we should do the focusable check and the while sentence.

e.g.
```javascript
methods: {
  ...
  getNextFocusableSibling(element) {
    let sibling = focusedElement.nextElementSibling;
    while (sibling && !isFocusable(sibling)) {
      sibling = sibling.nextElementSibling;
    }
    return sibling;
  }
}
```
and lets refactor the definition of these variables `prevSibling` and `sibling` to use the result of these methods.

**Comment by AlexVelezLl** [comment]
Hey @Sahil-Sinha-11. Yes!! It should be working like that, when we close the dropdown, the last focused element is the element that should be focused. Thank you!! Loking forward to see this change pushed in the PR :100:.

> PS: sorry for the late reply, actually my university exams are next week so quite loaded with tests. 😅

No worriees! :sweat_smile: There is no rush, please take your time :hugs:.

**Comment by Sahil-Sinha-11** [comment]
Hey @AlexVelezLl, I made the changes, please review it, thanks.

File: lib/KDropdownMenu.vue [hunk 3]
```diff
@@ -32,6 +32,7 @@
 <script>
 
   import { computed } from '@vue/composition-api';
+  // import { get } from 'lodash';
```
Comment (AlexVelezLl) [inline lib/KDropdownMenu.vue]: We can get rid of this line

File: lib/KDropdownMenu.vue [hunk 4]
```diff
@@ -147,6 +149,7 @@
       handleOpen() {
         this.$nextTick(() => this.$nextTick(() => this.setFocus()));
         window.addEventListener('keydown', this.handleOpenMenuNavigation, true);
+        this.lastFocusElement = document.activeElement;
```
Comment (AlexVelezLl) [inline lib/KDropdownMenu.vue]: Although there is no problem with having this line as the last line of the `handleOpen` method, we can move it to be the first line of the method, so the intention of storing the last focused element before we focus anything else is clearer :).

File: lib/KDropdownMenu.vue [hunk 5]
```diff
@@ -162,8 +165,31 @@
         ) {
           this.focusOnButton();
         }
+
+        if (this.lastFocusElement) {
```
Comment (AlexVelezLl) [inline lib/KDropdownMenu.vue]: Above this, you can see there is a call to the `this.focusOnButton()` method, which apparently was an old behaviour we had in KDropdownMenu, but its no longer useful as now KDropdownMenu doesnt render any button anymore.

But if in the past, we were making this call in those conditions, it was for some reason (perhaps because of an edge case im not aware of), but to play safe, lets just replace that `focusOnButton()` call with this lastFocusElement call, for this focus to occur on those conditions too, so we would have something like:
```javascript
        if (
          popover.contains(focusedElement) &&
          (focusedElement.classList.contains('ui-popover') ||
            focusedElement.classList.contains('ui-popover-focus-redirector') ||
            focusedElement.classList.contains('ui-menu-option'))
        ) {
          if (this.lastFocusElement) {
            this.lastFocusElement.focus();
          }
        }
```
And then we can remove the `focusOnButton` method :).

File: lib/KDropdownMenu.vue [hunk 6]
```diff
@@ -175,19 +201,27 @@
         const popoverIsOpen = popover.clientWidth > 0 && popover.clientHeight > 0;
         // set current element and its siblings
         let focusedElement = document.activeElement;
-        let sibling = focusedElement.nextElementSibling;
-        let prevSibling = focusedElement.previousElementSibling;
+        // let sibling = focusedElement.nextElementSibling;
```
Comment (AlexVelezLl) [inline lib/KDropdownMenu.vue]: Great catch! We dont need to make these calls always. We can remove these lines too.

File: lib/KDropdownMenu.vue [hunk 7]
```diff
@@ -175,19 +201,27 @@
...
+        //function to check if the sibling is divider
+        // const isFocusable = element => element && element.tabIndex >= 0;
 
         // manage rotating through the options using arrow keys
         // UP arrow: .keyCode is depricated and should used only as a fallback
         if ((event.key == 'ArrowUp' || event.keyCode == 38) && popoverIsOpen) {
           event.preventDefault();
+
+          // Checking if previous sibling is divider and if yes then skip it
+          let prevSibling = this.getPreviousFocusableSibling(focusedElement);
```
Comment (AlexVelezLl) [inline lib/KDropdownMenu.vue]: lets define these `prevSibling` and `sibling` as const, as we wont need to reassign them anymore.

**Review by AlexVelezLl — CHANGES_REQUESTED** [review]
Woo :tada:. This is working soo smothly @Sahil-Sinha-11. Thank you!! I have left a couple of comments just for some code clean up, thanks!

**Comment by Sahil-Sinha-11** [comment]
Hey @AlexVelezLl, I made the suggested changes, please review them, thanks.

**Comment by AlexVelezLl** [comment]
Thank youu @Sahil-Sinha-11!! Code changes look good to me! :) . I have just opened a [PR in Kolibri](https://github.com/learningequality/kolibri/pull/12838) with your changes for QA to test this in Kolibri and confirming that this is the expected behaviour, after that we can merge your PR. Thanks @Sahil-Sinha-11! Good job :hugs:

**Review by AlexVelezLl — APPROVED** [review]
Thanks @Sahil-Sinha-11!

**Comment by MisRob** [comment]
Thanks @Sahil-Sinha-11 and @AlexVelezLl, good chunk of work here :)!
