### PR TITLE
Fix KSelect overflows

### LINKED ISSUE #1066: [KSelect] Overflowed display value
❌ **This issue is not open for contribution. Visit <a href="https://learningequality.org/contributing-to-our-open-code-base/" target="_blank">Contributing guidelines</a>** to learn about the contributing process and how to find suitable issues.

## Observed behavior

When an option label is too long, the display value overflows.

Image

## Expected behavior

The text should be truncated or wrapped in a new line.

## Steps to reproduce

Render a KSelect with a long label option, and select it.

### PR DESCRIPTION
**Pull request by AlexVelezLl**
## Description

Fixes KSelect overflow by setting a width: 100% value to the `ui-select-content` div. Also turned the clear button small to avoid vertical overflows on button hover.

#### Issue addressed
Closes #1066.

### Before/after screenshots

| Before | After |
| --- | --- |
| image | image |
| image | image |

## Changelog

  - **Description:** Fixes KSelect content being overflowed when there was a selected option with a long label.
  - **Products impact:** bugfix.
  - **Addresses:** https://github.com/learningequality/kolibri-design-system/issues/1066.
  - **Components:** KSelect.
  - **Breaking:** no
  - **Impacts a11y:** no
  - **Guidance:** .

  - **Description:** Turns clear button to be small to avoid vertical overflow on button hover.
  - **Products impact:** bugfix.
  - **Addresses:** https://github.com/learningequality/kolibri-design-system/issues/1066.
  - **Components:** KSelect.
  - **Breaking:** no
  - **Impacts a11y:** no
  - **Guidance:** .

### CODE REVIEW

File: docs/pages/kselect.vue [hunk 1]
```diff
@@ -93,7 +93,7 @@
         exampleData: {},
         options: [
           {
-            label: 'Somebody',
+            label: 'This is a very very very very very long label',
```
Comment (MisRob) [inline docs/pages/kselect.vue]: Rather than utilizing documentation for a specific use-case that we don't really document on its own, a visual test may be more suitable?

**Review by MisRob — APPROVED** [review]
Thank you @AlexVelezLl, looks very nice.

Just one note for your consideration, nothing blocking.

File: docs/pages/kselect.vue (hunk 1 above)
Comment (AlexVelezLl) [reply docs/pages/kselect.vue]: Oh, this was just for testing purposes, I was planning to remove it after review. And yes, visual tests for this will be the best approach. Perhaps we can add it after #1050 is merged?

Comment (MisRob) [reply docs/pages/kselect.vue]: @AlexVelezLl I've just merged https://github.com/learningequality/kolibri-design-system/pull/1050 so you don't need to open follow-up or have conflicts. If it's easier, feel free to rebase, and push the new test here.

Also no matter if you do so or not now, feel free to merge without waiting for me so this work can be in today's patch. I consider the PR approved! Thanks :)

Comment (AlexVelezLl) [reply docs/pages/kselect.vue]: Thanks @MisRob! Just added them. I ran the tests locally and looks as expected, so not gonna run them again in this PR, to save some screenshots, as they will be run on develop anyways :sweat_smile:. Thank you!
