### PR TITLE
Fix ktabs extra space

### LINKED ISSUE #12297: Tabs cover dividing line
## Observed behavior
Noticed by @AlexVelezLl during 0.17.0-alpha0 bug bash 
image

## Expected behavior
The spacing of the tab should not cover the dividing line, it looks broken

## Steps to reproduce
Navigate to "plan" section in coach (likely exists throughout coach where we have this tab pattern) 

## Context
0.17.0-alpha0

### PR DESCRIPTION
**Pull request by AlexVelezLl**
## Description

Having an inline-block element with an `overflow: hidden` style causes an extra white space in its parent. See: https://stackoverflow.com/questions/23529369/why-does-x-overflowhidden-cause-extra-space-below.

#### Issue addressed
Needed to close https://github.com/learningequality/kolibri/issues/12297.

### Before/after screenshots

Before: 
image

After:
image

## Changelog

- [#673]
  - **Description:** Remove white space below Ktabs
  - **Products impact:** bugfix.
  - **Addresses:** https://github.com/learningequality/kolibri/issues/12297.
  - **Components:** KTabsList, KTabs, KTabsPanel.
  - **Breaking:** no
  - **Impacts a11y:**no
  - **Guidance:** .

[#673]: https://github.com/learningequality/kolibri-design-system/pull/673

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical and brittle code paths are covered by unit tests
- [ ] The change is described in the changelog section above

## Reviewer guidance

- [x] Is the code clean and well-commented?
- [ ] Are there tests for this change?
- [ ] Are all UI components LTR and RTL compliant (if applicable)?
- [ ] _Add other things to check for here_

## After review

- [x] The changelog item has been pasted to the `CHANGELOG.md`

### CODE REVIEW

File: lib/tabs/KTabsList.vue [hunk 1]
```diff
@@ -310,6 +310,9 @@
     border-top-left-radius: $radius;
     border-top-right-radius: $radius;
     transition: background-color $core-time ease;
+    // Setting vertical align here to prevent an extra space below the tabs
+    // https://stackoverflow.com/questions/23529369/why-does-x-overflowhidden-cause-extra-space-below
```
Comment (nucleogenesis) [inline lib/tabs/KTabsList.vue:314]: Great context here thanks for this!

**Review by nucleogenesis — APPROVED** [review]
Code changes here LGTM - tested in Kolibri and things look right to me! Thanks Alex

**Comment by AlexVelezLl** [comment]
Thank you @nucleogenesis!
