### PR TITLE
Corrected kdaterange month and year display and removed font-family

### LINKED ISSUE #405: XState warning
## Product
Noticed in Kolibri frontend tests

## Expected behavior
No warnings just from importing KDS

## Actual behavior
This warning gets shown repeatedly:
```
    console.warn
      It is highly recommended to set `predictableActionArguments` to `true` when using `createMachine`. https://xstate.js.org/docs/guides/actions.html
```

## Steps to reproduce the issue
Run a test in Kolibri.

### PR DESCRIPTION
**Pull request by LianaHarris360**
## Description

This PR fixes the incorrect display of the _Month Year_ on the `KDateRange` calendar when the previous month is December of last year and the current month is January. Previously, the left side of the calendar was incorrectly set to December of this year and the right side of the calendar was set to January of next year.

The `font-family` declaration has also been removed from `KDateCalendar` as it was unnecessary and caused implementation issues when `KDateRange` is used in Kolibri. 

Added `predictableActionArguments: true` to xstate validation machine to fix console warning based on XState Docs recommendations found [here](https://xstate.js.org/docs/guides/actions.html).  

#### Issue addressed
Fixes #405 

### Before/after screenshots

Before, incorrect _Month Year_ display
CorrectKDateRange

After, correct _Month Year_ display
IncorrectKDateRange

## Steps to test

1. Open KDateRange calendar modal demo.
2. Confirm that left side of calendar displays December of last year and the right side of the calendar displays January of this year.

### At a high level, how did you implement this?

The `activeMonth` (the month that is displayed on the left side of the calendar) is set with `new Date().getMonth() - 1`. 

When `new Date().getMonth()`  returns `0` for January, the value returned from `new Date().getMonth() - 1` is `-1` however, it should be `11`, for December. Now if `new Date().getMonth() - 1` returns `-1`, `activeMonth` is instead set to `11`.

In `created()`, if `activeMonth` is `11`, `activeYearStart` is set to last year.

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical and brittle code paths are covered by unit tests
- [ ] The change has been added to the `changelog`

## Reviewer guidance

- [ ] Is the code clean and well-commented?
- [ ] Are there tests for this change?
- [ ] Are all UI components LTR and RTL compliant (if applicable)?
- [ ] _Add other things to check for here_

## Comments

I'm not sure if this change needs to be added in the `changelog` or not.

### CODE REVIEW

**Review by akolson — APPROVED** [review]
Thanks @LianaHarris360. the fix LGTM!

File: lib/KDateRange/ValidationMachine.js [hunk 1]
```diff
@@ -98,6 +98,7 @@ export const initialContext = {
 };
 
 export const validationMachine = createMachine({
+  predictableActionArguments: true,
```
Comment (nucleogenesis) [inline lib/KDateRange/ValidationMachine.js:101]: Ooh - I wonder if I should include this in the SetupWizard machine too!

**Review by nucleogenesis — APPROVED** [review]
LGTM
