### PR TITLE
Fixed case-sensitive sorting for KTable

### LINKED ISSUE #852: [KTable]: Improve built-in sorting to handle case-insensitive string sorting
## Product
Kolibri
## Actual behavior

The uppercase characters are sorted before lowercase characters, leading to inconsistent and unexpected results for users.
Image

## Expected behavior

The characters should be sorted in alphabetical order irrespective of their case.

## Steps to reproduce the issue
 Go to Kolibri > Facility > Classes
Try adding Classes with different initial letter cases.
See how they are displayed in table when sorted according to class name.

### PR DESCRIPTION
**Pull request by BabyElias**
## Description

This PR fixes the issue caused by case-sensitive sorting for KTable where uppercase characters were sorted before lowercase characters. `toLocaleLowerCase()` method has been used to ensure internationalisation concerns are addressed while standardising strings to lower case for comparison.

#### Issue addressed

Closes #852 

### Before/after screenshots

Before - 
table sort
After -
table sort 2

## Changelog

  - **Description:** Makes KTable sorting case-insensitive and internationalized
  - **Products impact:** bugfix
  - **Addresses:** https://github.com/learningequality/kolibri-design-system/issues/852
  - **Components:** KTable
  - **Breaking:** No
  - **Impacts a11y:** No
  - **Guidance:** NA

### Does this introduce any tech-debt items?

No

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical and brittle code paths are covered by unit tests
- [ ] The change is described in the changelog section above

## Reviewer guidance

- [ ] Is the code clean and well-commented?
- [ ] Are there tests for this change?
- [ ] Are all UI components LTR and RTL compliant (if applicable)?
- [ ] _Add other things to check for here_

### CODE REVIEW

**Comment by MisRob** [comment]
Thank you for keeping taking care of the table, @BabyElias :) I will invite my colleague @AllanOXDi for review. One suggestion from me would be to add a unit test to cover this, if you'd like to do so meanwhile.

**Comment by MisRob** [comment]
@AllanOXDi for reference, this issue https://github.com/learningequality/kolibri-design-system/issues/852 was open by @BabyElias after we agreed together it's expected behavior.

**Comment by BabyElias** [comment]
I have updated the test cases to cover strings having both lower and uppercase characters.

File: lib/KTable/useSorting/index.js [hunk 1]
```diff
@@ -24,25 +24,39 @@ export default function useSorting(headers, rows, defaultSort, disableBuiltinSor
...
+  /**
+   * Helper function to get the value for sorting.
+   * @param {Object} row - The row object.
+   * @param {Number} index - The index of the column to sort by.
+   * @returns {any} - The value to be used for sorting.
+   */
+  const getSortValue = (row, index) => {
+    const value = row[index];
+    if (typeof value === 'string') {
+      return value.toString().toLocaleLowerCase();
```
Comment (AllanOXDi) [inline lib/KTable/useSorting/index.js:36]: One minor issue- Adding a check to ensure that the value is not null or undefined before attempting to convert it to lowercase, this would prevent potential errors if the data has missing values.

Comment (BabyElias) [reply lib/KTable/useSorting/index.js:36]: Added check for null values.

File: lib/KTable/useSorting/index.js [hunk 2]
```diff
@@ -24,25 +24,39 @@ export default function useSorting(headers, rows, defaultSort, disableBuiltinSor
   const sortKey = ref(null);
   const sortOrder = ref(null);
 
+  /**
+   * Helper function to get the value for sorting.
+   * @param {Object} row - The row object.
+   * @param {Number} index - The index of the column to sort by.
+   * @returns {any} - The value to be used for sorting.
+   */
+  const getSortValue = (row, index) => {
```
Comment (MisRob) [inline lib/KTable/useSorting/index.js:33]: Neat

**Comment by MisRob** [comment]
This looks good to me too. @AllanOXDi feel free to merge after you've seen the latest changes if you think all is ready :) Thanks both!

**Comment by MisRob** [comment]
I made a small tweak to the changelog "Description" to be a bit more specific.

**Review by AllanOXDi — APPROVED** [review]
Looks good to me too! Thanks @BabyElias
